export const GET_USER_LIST  = 'GET_USER_LIST';
export const GET_SAW_SAWLIST  = 'GET_SAW_SAWLIST';
export const GET_SAW_JOBLIST = 'GET_SAW_JOBLIST';
export const GET_SAW_JOBDETAILSLIST = 'GET_SAW_JOBDETAILSLIST';

export const GET_SAW_STATUS_TABLE = 'GET_SAW_STATUS_TABLE';
export const SET_SAW_STATUS_SHOW_POPUP = 'SET_SAW_STATUS_SHOW_POPUP';
export const ADD_SAW_STATUS_SUCCESS = 'ADD_SAW_STATUS_SUCCESS';
export const ADD_SAW_STATUS_FAILURE = 'ADD_SAW_STATUS_FAILURE';
export const UPDATE_SAW_STATUS_SUCCESS = 'UPDATE_SAW_STATUS_SUCCESS';
export const UPDATE_SAW_STATUS_FAILURE = 'UPDATE_SAW_STATUS_FAILURE';
export const DELETE_SAW_STATUS_SUCCESS = 'DELETE_SAW_STATUS_SUCCESS';
export const DELETE_SAW_STATUS_FAILURE = 'DELETE_SAW_STATUS_FAILURE';
export const SET_SELECTED_SAW = 'SET_SELECTED_SAW';
export const SET_SELECTED_JOBDETAIL = 'SET_SELECTED_JOBDETAIL';
export const SET_SELECTED_JOB = 'SET_SELECTED_JOB';
export const GET_SAW_PROFILECUTTING = 'GET_SAW_PROFILECUTTING';
export const GET_SAW_CUTLIST = 'GET_SAW_CUTLIST'
//-----------------tables---------------------
export const GET_SAW_SCHEDULES = 'GET_SAW_SCHEDULES'
export const GET_SAW_BARS = 'GET_SAW_BARS'
export const GET_SAW_CUTS = 'GET_SAW_CUTS'
export const GET_SAW_STATUS = 'GET_SAW_STATUS'
export const GET_SAW_FLAGS = 'GET_SAW_FLAGS'
export const GET_FLAGGED_JOB = 'GET_FLAGGED_JOB'
//------------------------------------------------
export const GET_SAW_PRINTS = 'GET_SAW_PRINTS'
export const GET_LOCATIONS = 'GET_LOCATIONS'



